openapi: 3.2.0
info:
  title: Administration Feature Sets API
  version: 1.0.0
servers:
- url: https://rls.congacloud.com/api/revenue-admin/v1
security:
- Bearer: []
tags:
- name: Feature Sets
paths:
  /feature-sets:
    delete:
      tags:
      - Feature Sets
      summary: Delete feature sets
      description: Deletes multiple feature sets.
      requestBody:
        description: The list of feature sets to delete
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeatureSet'
            example:
            - Id: Id of the record to delete
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeatureSet'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeatureSet'
      responses:
        '200':
          description: OK
    get:
      tags:
      - Feature Sets
      summary: Retrieve feature sets
      description: Retrieves the collection of feature sets.
      parameters:
      - name: filter
        in: query
        description: Optional filter parameters
        schema:
          type: array
          items:
            type: string
      - name: sort
        in: query
        description: Optional sort parameter
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
          format: int32
          default: 1
      - name: limit
        in: query
        description: Number of items per page
        schema:
          type: integer
          format: int32
          default: 50
      - name: includes
        in: query
        description: Optional related entities to include
        schema:
          type: array
          items:
            type: string
      - name: field
        in: query
        description: Pass Comma separated mulitple fields
        schema:
          type: array
          items:
            type: string
      - name: filterExpression
        in: query
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    patch:
      tags:
      - Feature Sets
      summary: Update feature sets
      description: Updates multiple feature sets.
      requestBody:
        description: The list of feature sets with updated data
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
            example:
            - Name: FeatureSetName
              Description: Feature Set description
              Sequence: 1
              Id: Id of the record
          text/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
          application/*+json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
      responses:
        '200':
          description: OK
    post:
      tags:
      - Feature Sets
      summary: Create feature sets
      description: Creates multiple feature sets.
      requestBody:
        description: The list of feature sets to create
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeatureSet'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeatureSet'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FeatureSet'
      responses:
        '200':
          description: OK
  /feature-sets/{Id}:
    delete:
      tags:
      - Feature Sets
      summary: Delete a feature set
      description: Deletes a single feature set by its identifier.
      parameters:
      - name: Id
        in: path
        description: The identifier of the feature set to delete
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
    get:
      tags:
      - Feature Sets
      summary: Retrieve a feature set
      description: Retrieves a single feature set by its identifier.
      parameters:
      - name: Id
        in: path
        description: The identifier of the feature set
        required: true
        schema:
          type: string
      - name: includes
        in: query
        description: Optional related entities to include
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/FeatureSet'
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureSet'
            text/json:
              schema:
                $ref: '#/components/schemas/FeatureSet'
    patch:
      tags:
      - Feature Sets
      summary: Update a feature set
      description: Updates a single feature set.
      parameters:
      - name: Id
        in: path
        description: The identifier of the feature set to update
        required: true
        schema:
          type: string
      requestBody:
        description: The updated data of the feature set
        content:
          application/json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Name: FeatureSetName
              Description: Feature Set description
              Sequence: 1
          text/json:
            schema:
              type: object
              additionalProperties: {}
          application/*+json:
            schema:
              type: object
              additionalProperties: {}
      responses:
        '200':
          description: OK
  /feature-sets/{parentId}/product-features:
    delete:
      tags:
      - Feature Sets
      summary: Delete product features
      description: Deletes multiple junction records.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      requestBody:
        description: The list of records to delete
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductFeature'
            example:
            - Id: Id of the record to delete
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductFeature'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductFeature'
      responses:
        '200':
          description: OK
    get:
      tags:
      - Feature Sets
      summary: Retrieve product features
      description: Retrieves a list of junction records.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      - name: filter
        in: query
        description: The filter conditions
        schema:
          type: array
          items:
            type: string
      - name: sort
        in: query
        description: The sort expression
        schema:
          type: string
      - name: page
        in: query
        description: The page number
        schema:
          type: integer
          format: int32
          default: 1
      - name: limit
        in: query
        description: The maximum number of records to retrieve per page
        schema:
          type: integer
          format: int32
          default: 50
      - name: includes
        in: query
        description: The related entities to include
        schema:
          type: array
          items:
            type: string
      - name: field
        in: query
        description: Pass Comma separated mulitple fields
        schema:
          type: array
          items:
            type: string
      - name: filterExpression
        in: query
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    patch:
      tags:
      - Feature Sets
      summary: Update product features
      description: Updates multiple junction records.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      requestBody:
        description: The list of records to update
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
            example:
            - Name: Name of the record
              FeatureSet:
                Id: FeatureSet-Id
                Name: FeatureSet-Name
              Id: Id of the record
          text/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
          application/*+json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
      responses:
        '200':
          description: OK
    post:
      tags:
      - Feature Sets
      summary: Create product features
      description: Creates multiple junction records.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      requestBody:
        description: The list of records to create
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductFeature'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductFeature'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductFeature'
      responses:
        '200':
          description: OK
  /feature-sets/{parentId}/product-features/{id}:
    delete:
      tags:
      - Feature Sets
      summary: Delete a product feature
      description: Deletes a specific junction record.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: The ID of the junction record to delete
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
    get:
      tags:
      - Feature Sets
      summary: Retrieve a product feature
      description: Retrieves a specific junction record.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: The ID of the junction record
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    patch:
      tags:
      - Feature Sets
      summary: Update a product feature
      description: Updates a specific junction record.
      parameters:
      - name: parentId
        in: path
        description: The ID of the parent entity
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: The ID of the junction record to update
        required: true
        schema:
          type: string
      requestBody:
        description: The updated record
        content:
          application/json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Name: Name of the record
              FeatureSet:
                Id: FeatureSet-Id
                Name: FeatureSet-Name
          text/json:
            schema:
              type: object
              additionalProperties: {}
          application/*+json:
            schema:
              type: object
              additionalProperties: {}
      responses:
        '200':
          description: OK
components:
  schemas:
    FeatureSet:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
        CreatedBy:
          $ref: '#/components/schemas/LookupObject'
        CreatedDate:
          type: string
          format: date-time
        ModifiedBy:
          $ref: '#/components/schemas/LookupObject'
        ModifiedDate:
          type: string
          format: date-time
        ExternalId:
          type:
          - string
          - 'null'
        ETag:
          type:
          - string
          - 'null'
        Description:
          type:
          - string
          - 'null'
        Sequence:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: {}
      example:
        Name: FeatureSetName
        Description: Feature Set description
        Sequence: 1
    LookupObject:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
      additionalProperties: false
    ProductFeature:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
        CreatedBy:
          $ref: '#/components/schemas/LookupObject'
        CreatedDate:
          type: string
          format: date-time
        ModifiedBy:
          $ref: '#/components/schemas/LookupObject'
        ModifiedDate:
          type: string
          format: date-time
        ExternalId:
          type:
          - string
          - 'null'
        ETag:
          type:
          - string
          - 'null'
        FeatureSet:
          $ref: '#/components/schemas/LookupObject'
        IncludedFeatures:
          type:
          - string
          - 'null'
        Product:
          $ref: '#/components/schemas/LookupObject'
        Sequence:
          type:
          - integer
          - 'null'
          format: int32
      additionalProperties: {}
      example:
        Name: Name of the record
        FeatureSet:
          Id: FeatureSet-Id
          Name: FeatureSet-Name
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
