openapi: 3.2.0
info:
  title: Administration Deal Guidance Dimensions API
  version: 1.0.0
servers:
- url: https://rls.congacloud.com/api/revenue-admin/v1
security:
- Bearer: []
tags:
- name: Deal Guidance Dimensions
paths:
  /deal-guidance-dimensions:
    delete:
      tags:
      - Deal Guidance Dimensions
      summary: Delete deal guidance dimensions
      description: Deletes one or more dimensions based on the payload passed.
      requestBody:
        description: The list of Deal Guidance Dimensions to delete
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DealGuidanceDimension'
            example:
            - Id: Id of the record to delete
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DealGuidanceDimension'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DealGuidanceDimension'
      responses:
        '200':
          description: OK
    get:
      tags:
      - Deal Guidance Dimensions
      summary: Retrieve deal guidance dimensions
      description: Retrieves a the list of dimensions.
      parameters:
      - name: filter
        in: query
        description: Optional filter parameters
        schema:
          type: array
          items:
            type: string
      - name: sort
        in: query
        description: Optional sort parameter
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
          format: int32
          default: 1
      - name: limit
        in: query
        description: Number of items per page
        schema:
          type: integer
          format: int32
          default: 50
      - name: includes
        in: query
        description: Optional related entities to include
        schema:
          type: array
          items:
            type: string
      - name: field
        in: query
        description: Pass Comma separated mulitple fields
        schema:
          type: array
          items:
            type: string
      - name: filterExpression
        in: query
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    patch:
      tags:
      - Deal Guidance Dimensions
      summary: Update deal guidance dimensions
      description: Updates one or more dimensions based on the payload passed.
      requestBody:
        description: The list of Deal Guidance Dimensions with updated data
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
            example:
            - Name: DealGuidanceDimensionName
              BusinessObject: Business_object
              Datasource: Datasource
              Description: Deal Guidance Dimension description
              DimensionType: Dimension_type
              Id: Id of the record
          text/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
          application/*+json:
            schema:
              type: array
              items:
                type: object
                additionalProperties: {}
      responses:
        '200':
          description: OK
    post:
      tags:
      - Deal Guidance Dimensions
      summary: Create deal guidance dimensions
      description: 'Creates one or more dimensions on a field so that you can set deal rule criteria based on the defined dimensions for a deal evaluation.



        After creating dimensions, create a dimension set and make use of the newly-created dimensions.'
      requestBody:
        description: The list of Deal Guidance Dimensions to create
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DealGuidanceDimension'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DealGuidanceDimension'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DealGuidanceDimension'
      responses:
        '200':
          description: OK
  /deal-guidance-dimensions/{Id}:
    delete:
      tags:
      - Deal Guidance Dimensions
      summary: Delete a deal guidance dimension
      description: Deletes a details of a dimension record.
      parameters:
      - name: Id
        in: path
        description: The identifier of the Deal Guidance Dimension to delete
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
    get:
      tags:
      - Deal Guidance Dimensions
      summary: Retrieve a deal guidance dimension
      description: Retrieves a single deal guidance dimension by its identifier.
      parameters:
      - name: Id
        in: path
        description: The identifier of the Deal Guidance Dimension
        required: true
        schema:
          type: string
      - name: includes
        in: query
        description: Optional related entities to include
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
    patch:
      tags:
      - Deal Guidance Dimensions
      summary: Update a deal guidance dimension
      description: Updates the details of a dimension record.
      parameters:
      - name: Id
        in: path
        description: The identifier of the Deal Guidance Dimension to update
        required: true
        schema:
          type: string
      requestBody:
        description: The updated data of the Deal Guidance Dimension
        content:
          application/json:
            schema:
              type: object
              additionalProperties: {}
            example:
              Name: DealGuidanceDimensionName
              BusinessObject: Business_object
              Datasource: Datasource
              Description: Deal Guidance Dimension description
              DimensionType: Dimension_type
          text/json:
            schema:
              type: object
              additionalProperties: {}
          application/*+json:
            schema:
              type: object
              additionalProperties: {}
      responses:
        '200':
          description: OK
components:
  schemas:
    LookupObject:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
      additionalProperties: false
    DealGuidanceDimension:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
        CreatedBy:
          $ref: '#/components/schemas/LookupObject'
        CreatedDate:
          type: string
          format: date-time
        ModifiedBy:
          $ref: '#/components/schemas/LookupObject'
        ModifiedDate:
          type: string
          format: date-time
        ExternalId:
          type:
          - string
          - 'null'
        ETag:
          type:
          - string
          - 'null'
        BusinessObject:
          type:
          - string
          - 'null'
        Datasource:
          type:
          - string
          - 'null'
        Description:
          type:
          - string
          - 'null'
        DimensionType:
          type:
          - string
          - 'null'
      additionalProperties: {}
      example:
        Name: DealGuidanceDimensionName
        BusinessObject: Business_object
        Datasource: Datasource
        Description: Deal Guidance Dimension description
        DimensionType: Dimension_type
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
