openapi: 3.2.0
info:
  title: Email Profile API
  version: v1
servers:
- url: https://rls.congacloud.com
security:
- Bearer: []
tags:
- name: Email Profile
paths:
  /api/email/v1/email-profiles:
    post:
      tags:
      - Email Profile
      summary: Create a new email profile
      description: Validates and creates a new email profile.
      requestBody:
        description: The details of the email profile to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailProfile'
            example:
              EmailAddress: test@conga.com
              Name: Default ProfileName
              DisplayName: Default Profile
              Id: null
              CreatedBy: null
              CreatedDate: '0001-01-01T00:00:00'
              ModifiedBy: null
              ModifiedDate: '0001-01-01T00:00:00'
              ExternalId: null
              ETag: null
          text/json:
            schema:
              $ref: '#/components/schemas/EmailProfile'
            example:
              EmailAddress: test@conga.com
              Name: Default ProfileName
              DisplayName: Default Profile
              Id: null
              CreatedBy: null
              CreatedDate: '0001-01-01T00:00:00'
              ModifiedBy: null
              ModifiedDate: '0001-01-01T00:00:00'
              ExternalId: null
              ETag: null
          application/*+json:
            schema:
              $ref: '#/components/schemas/EmailProfile'
            example:
              EmailAddress: test@conga.com
              Name: Default ProfileName
              DisplayName: Default Profile
              Id: null
              CreatedBy: null
              CreatedDate: '0001-01-01T00:00:00'
              ModifiedBy: null
              ModifiedDate: '0001-01-01T00:00:00'
              ExternalId: null
              ETag: null
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailProfileAPIResponse'
              example:
                Success: true
                Data:
                  EmailAddress: test@conga.com
                  Name: Default ProfileName
                  DisplayName: Default Profile
                  Id: 7550b532-cdc0-416d-8ba6-5f6ffd311a8d
                  CreatedBy: null
                  CreatedDate: '0001-01-01T00:00:00'
                  ModifiedBy: null
                  ModifiedDate: '0001-01-01T00:00:00'
                  ExternalId: null
                  ETag: null
                StatusCode: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /api/email/v1/email-profiles/{name}:
    delete:
      tags:
      - Email Profile
      summary: Delete the email profile
      description: Removes the email profile based on the email profile name.
      parameters:
      - name: name
        in: path
        description: The unique name of the email profile to be deleted.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringAPIResponse'
              example:
                Success: true
                Data: EmailTemplate 887f6f7f-239b-4afd-ac6e-81877466b441 is deleted successfully.
                StatusCode: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    get:
      tags:
      - Email Profile
      summary: Get an email profile by name
      description: Validates and retrieves the email profile based on the email profile name.
      parameters:
      - name: name
        in: path
        description: The unique name of the email profile to retrieve.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailProfileAPIResponse'
              example:
                Success: true
                Data:
                  EmailAddress: test@conga.com
                  Name: Default ProfileName
                  DisplayName: Default Profile
                  Id: bf5c1cad-6004-4272-b359-d93bfb72952f
                  CreatedBy: null
                  CreatedDate: '0001-01-01T00:00:00'
                  ModifiedBy: null
                  ModifiedDate: '0001-01-01T00:00:00'
                  ExternalId: null
                  ETag: null
                StatusCode: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
      - Email Profile
      summary: Update an email profile
      description: Validates and updates the email profile based on the email profile Name.
      parameters:
      - name: name
        in: path
        description: The unique name of the email profile to be updated.
        required: true
        schema:
          type: string
      requestBody:
        description: The updated details of the email profile.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailProfile'
            example:
              EmailAddress: test@conga.com
              Name: Default ProfileName
              DisplayName: Default Profile
              Id: null
              CreatedBy: null
              CreatedDate: '0001-01-01T00:00:00'
              ModifiedBy: null
              ModifiedDate: '0001-01-01T00:00:00'
              ExternalId: null
              ETag: null
          text/json:
            schema:
              $ref: '#/components/schemas/EmailProfile'
            example:
              EmailAddress: test@conga.com
              Name: Default ProfileName
              DisplayName: Default Profile
              Id: null
              CreatedBy: null
              CreatedDate: '0001-01-01T00:00:00'
              ModifiedBy: null
              ModifiedDate: '0001-01-01T00:00:00'
              ExternalId: null
              ETag: null
          application/*+json:
            schema:
              $ref: '#/components/schemas/EmailProfile'
            example:
              EmailAddress: test@conga.com
              Name: Default ProfileName
              DisplayName: Default Profile
              Id: null
              CreatedBy: null
              CreatedDate: '0001-01-01T00:00:00'
              ModifiedBy: null
              ModifiedDate: '0001-01-01T00:00:00'
              ExternalId: null
              ETag: null
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooleanNullableAPIResponse'
              example:
                Success: true
                Data: true
                StatusCode: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    EmailProfile:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        CreatedBy:
          $ref: '#/components/schemas/LookupObject'
        CreatedDate:
          type: string
          format: date-time
        ModifiedBy:
          $ref: '#/components/schemas/LookupObject'
        ModifiedDate:
          type: string
          format: date-time
        ExternalId:
          type:
          - string
          - 'null'
        ETag:
          type:
          - string
          - 'null'
        EmailAddress:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
        DisplayName:
          type:
          - string
          - 'null'
      additionalProperties: {}
    LookupObject:
      type: object
      properties:
        Id:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
      additionalProperties: false
    ErrorDetail:
      type: object
      properties:
        Message:
          type:
          - string
          - 'null'
      additionalProperties: false
    EmailProfileAPIResponse:
      type: object
      properties:
        Success:
          type: boolean
        RecordCount:
          type:
          - integer
          - 'null'
          format: int64
        Data:
          $ref: '#/components/schemas/EmailProfile'
        Errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
        Profile:
          type:
          - string
          - 'null'
        TotalTime:
          type: number
          format: float
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        HasMoreRecords:
          type:
          - boolean
          - 'null'
        NextCursor:
          type:
          - string
          - 'null'
        Warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
      additionalProperties: false
    BooleanNullableAPIResponse:
      type: object
      properties:
        Success:
          type: boolean
        RecordCount:
          type:
          - integer
          - 'null'
          format: int64
        Data:
          type:
          - boolean
          - 'null'
        Errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
        Profile:
          type:
          - string
          - 'null'
        TotalTime:
          type: number
          format: float
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        HasMoreRecords:
          type:
          - boolean
          - 'null'
        NextCursor:
          type:
          - string
          - 'null'
        Warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
      additionalProperties: false
    HttpStatusCode:
      enum:
      - Continue
      - SwitchingProtocols
      - Processing
      - EarlyHints
      - OK
      - Created
      - Accepted
      - NonAuthoritativeInformation
      - NoContent
      - ResetContent
      - PartialContent
      - MultiStatus
      - AlreadyReported
      - IMUsed
      - MultipleChoices
      - MovedPermanently
      - Found
      - SeeOther
      - NotModified
      - UseProxy
      - Unused
      - TemporaryRedirect
      - PermanentRedirect
      - BadRequest
      - Unauthorized
      - PaymentRequired
      - Forbidden
      - NotFound
      - MethodNotAllowed
      - NotAcceptable
      - ProxyAuthenticationRequired
      - RequestTimeout
      - Conflict
      - Gone
      - LengthRequired
      - PreconditionFailed
      - RequestEntityTooLarge
      - RequestUriTooLong
      - UnsupportedMediaType
      - RequestedRangeNotSatisfiable
      - ExpectationFailed
      - MisdirectedRequest
      - UnprocessableEntity
      - Locked
      - FailedDependency
      - UpgradeRequired
      - PreconditionRequired
      - TooManyRequests
      - RequestHeaderFieldsTooLarge
      - UnavailableForLegalReasons
      - InternalServerError
      - NotImplemented
      - BadGateway
      - ServiceUnavailable
      - GatewayTimeout
      - HttpVersionNotSupported
      - VariantAlsoNegotiates
      - InsufficientStorage
      - LoopDetected
      - NotExtended
      - NetworkAuthenticationRequired
      type: string
    StringAPIResponse:
      type: object
      properties:
        Success:
          type: boolean
        RecordCount:
          type:
          - integer
          - 'null'
          format: int64
        Data:
          type:
          - string
          - 'null'
        Errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
        Profile:
          type:
          - string
          - 'null'
        TotalTime:
          type: number
          format: float
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        HasMoreRecords:
          type:
          - boolean
          - 'null'
        NextCursor:
          type:
          - string
          - 'null'
        Warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
