openapi: 3.2.0
info:
  title: Schema Manager Dependent Picklist Definition API
  version: v1
servers:
- url: https://rls.congacloud.com
- url: https://preview-rls09.congacloud.com
security:
- bearerAuth: []
tags:
- name: Dependent Picklist Definition
paths:
  /api/schema/v1/objects/{objectName}/fields/{fieldName}/dependent-picklists:
    delete:
      tags:
      - Dependent Picklist Definition
      summary: Delete the dependent picklist
      description: Validates and removes the dependent picklist metadata for the given dependent field and object.
      parameters:
      - name: objectName
        in: path
        description: Name of the object containing the field
        required: true
        schema:
          type: string
      - name: fieldName
        in: path
        description: Name of the dependent field from which dependent picklist metadata is to be deleted
        required: true
        schema:
          type: string
      responses:
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    get:
      tags:
      - Dependent Picklist Definition
      summary: Get the dependent picklist
      description: Validates and fetches the dependent picklist metadata for the given dependent field name and object.
      parameters:
      - name: objectName
        in: path
        description: Name of the object containing the field
        required: true
        schema:
          type: string
      - name: fieldName
        in: path
        description: Name of the dependent field for which the dependent picklist metadata is to be fetched
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DependentPicklistMetadataAPIResponse'
              example:
                Success: true
                Data:
                  Name: BillingCity
                  DependentFieldName: BillingCity_c
                  ControllingFieldName: BillingState_c
                  ControllingAndDependentPicklistEntries:
                  - ControllingPicklistEntry: Gujarat
                    DependentPicklistEntries:
                    - Value: Ahmedabad
                      DisplayText: Ahmedabad
                      Sequence: 0
                      IsDeprecated: false
                  IsDeprecated: false
                StatusCode: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      tags:
      - Dependent Picklist Definition
      summary: Create a new dependent picklist mapping
      description: Validates and creates a new dependent picklist mapping for the given dependent field name and object.
      parameters:
      - name: objectName
        in: path
        description: Name of the object containing the fields
        required: true
        schema:
          type: string
      - name: fieldName
        in: path
        description: Name of the dependent field for which the dependent pickist mapping is to be created.
        required: true
        schema:
          type: string
      requestBody:
        description: Input for creating a dependent picklist mapping for the controlling and dependent fields.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DependentPicklistMetadataRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/DependentPicklistMetadataRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/DependentPicklistMetadataRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DependentPicklistMetadataAPIResponse'
              example:
                Success: true
                Data:
                  Name: BillingCity
                  DependentFieldName: BillingCity_c
                  ControllingFieldName: BillingState_c
                  ControllingAndDependentPicklistEntries:
                  - ControllingPicklistEntry: Gujarat
                    DependentPicklistEntries:
                    - Value: Ahmedabad
                      DisplayText: Ahmedabad
                      Sequence: 0
                      IsDeprecated: false
                  IsDeprecated: false
                StatusCode: Created
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
      - Dependent Picklist Definition
      summary: Update the dependent picklist
      description: Validates and updates the dependent picklist metadata for the given dependent field name and object.
      parameters:
      - name: objectName
        in: path
        description: Name of the object containing the field
        required: true
        schema:
          type: string
      - name: fieldName
        in: path
        description: Name of the dependent field for which the dependent picklist metadata is to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Dependent picklist metadata details to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DependentPicklistMetadataRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/DependentPicklistMetadataRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/DependentPicklistMetadataRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DependentPicklistMetadataAPIResponse'
              example:
                Success: true
                Data:
                  Name: BillingCity
                  DependentFieldName: BillingCity_c
                  ControllingFieldName: BillingState_c
                  ControllingAndDependentPicklistEntries:
                  - ControllingPicklistEntry: Gujarat
                    DependentPicklistEntries:
                    - Value: Ahmedabad
                      DisplayText: Ahmedabad
                      Sequence: 0
                      IsDeprecated: false
                  IsDeprecated: false
                StatusCode: Created
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    ControllingDependentPicklistEntryCreateRequest:
      type: object
      properties:
        ControllingPicklistEntry:
          type:
          - string
          - 'null'
          description: Controlling picklist entry of the picklist
        DependentPicklistEntries:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PicklistEntryCreateRequest'
          description: Collection of the dependent picklist values
      additionalProperties: false
      description: Controlling dependent picklist entry
    ControllingAndDependentPicklistEntry:
      type: object
      properties:
        ControllingPicklistEntry:
          type:
          - string
          - 'null'
        DependentPicklistEntries:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/PicklistEntry'
      additionalProperties: false
    PicklistEntry:
      type: object
      properties:
        Value:
          type:
          - string
          - 'null'
        DisplayText:
          type:
          - string
          - 'null'
        Sequence:
          type: integer
          format: int32
        IsDeprecated:
          type: boolean
      additionalProperties: false
    PicklistEntryCreateRequest:
      type: object
      properties:
        Value:
          type:
          - string
          - 'null'
          description: Value of the picklist entry
        DisplayText:
          type:
          - string
          - 'null'
          description: Display text of the picklist entry
        Sequence:
          type: integer
          description: Sequence of the picklist entry
          format: int32
      additionalProperties: false
    ErrorDetail:
      type: object
      properties:
        Message:
          type:
          - string
          - 'null'
      additionalProperties: false
    DependentPicklistMetadataAPIResponse:
      type: object
      properties:
        Success:
          type: boolean
        RecordCount:
          type:
          - integer
          - 'null'
          format: int64
        Data:
          $ref: '#/components/schemas/DependentPicklistMetadata'
        Errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
        Profile:
          type:
          - string
          - 'null'
        TotalTime:
          type: number
          format: float
        StatusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        HasMoreRecords:
          type:
          - boolean
          - 'null'
        NextCursor:
          type:
          - string
          - 'null'
        Warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ErrorDetail'
      additionalProperties: false
    DependentPicklistMetadata:
      type: object
      properties:
        Name:
          type:
          - string
          - 'null'
        DependentFieldName:
          type:
          - string
          - 'null'
        ControllingFieldName:
          type:
          - string
          - 'null'
        ControllingAndDependentPicklistEntries:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ControllingAndDependentPicklistEntry'
        IsDeprecated:
          type: boolean
      additionalProperties: false
    DependentPicklistMetadataRequest:
      type: object
      properties:
        Name:
          type:
          - string
          - 'null'
          description: Name of the dependent picklist
        DependentFieldName:
          type:
          - string
          - 'null'
          description: Dependent field name of the picklist
        ControllingFieldName:
          type:
          - string
          - 'null'
          description: Controlling field name of the picklist
        ControllingAndDependentPicklistEntries:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ControllingDependentPicklistEntryCreateRequest'
          description: Collection of the controlling and dependent picklist
      additionalProperties: false
    HttpStatusCode:
      enum:
      - Continue
      - SwitchingProtocols
      - Processing
      - EarlyHints
      - OK
      - Created
      - Accepted
      - NonAuthoritativeInformation
      - NoContent
      - ResetContent
      - PartialContent
      - MultiStatus
      - AlreadyReported
      - IMUsed
      - MultipleChoices
      - MovedPermanently
      - Found
      - SeeOther
      - NotModified
      - UseProxy
      - Unused
      - TemporaryRedirect
      - PermanentRedirect
      - BadRequest
      - Unauthorized
      - PaymentRequired
      - Forbidden
      - NotFound
      - MethodNotAllowed
      - NotAcceptable
      - ProxyAuthenticationRequired
      - RequestTimeout
      - Conflict
      - Gone
      - LengthRequired
      - PreconditionFailed
      - RequestEntityTooLarge
      - RequestUriTooLong
      - UnsupportedMediaType
      - RequestedRangeNotSatisfiable
      - ExpectationFailed
      - MisdirectedRequest
      - UnprocessableEntity
      - Locked
      - FailedDependency
      - UpgradeRequired
      - PreconditionRequired
      - TooManyRequests
      - RequestHeaderFieldsTooLarge
      - UnavailableForLegalReasons
      - InternalServerError
      - NotImplemented
      - BadGateway
      - ServiceUnavailable
      - GatewayTimeout
      - HttpVersionNotSupported
      - VariantAlsoNegotiates
      - InsufficientStorage
      - LoopDetected
      - NotExtended
      - NetworkAuthenticationRequired
      type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
